# Generated by Django 6.0.5 on 2026-06-07 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_customer_created_by'),
        ('products', '0002_rename_price_product_retail_price_and_more'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesorder',
            name='customer_name',
        ),
        migrations.RemoveField(
            model_name='salesorder',
            name='product_name',
        ),
        migrations.AddField(
            model_name='salesorder',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sales_orders', to='customers.customer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salesorder',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sales_orders', to='products.product'),
            preserve_default=False,
        ),
    ]
