# Generated by Django 6.0.5 on 2026-06-08 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_alter_salesorder_total_amount_salesorderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesorder',
            name='product',
        ),
        migrations.RemoveField(
            model_name='salesorder',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='salesorder',
            name='unit_price',
        ),
    ]
